name: Upload Python Package
on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2014_x86_64
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Initialize submodules
      run: git submodule update --init
    - name: Build static library
      run: |
        cd src/paula/celia
        mkdir build
        cd build
        cmake ..
        cmake --build .
    - name: Build python extension
      run: |
        python setup.py bdist_wheel

